server:
  port: 8761
spring:
  application:
    name: ead-service-registry

eureka:
  client:
    register-with-eureka: false  # nao se registrar nele mesmo
    fetch-registry: false        # clientes irao buscar o registro
